sudo: false
dist: bionic
language: rust

addons:
  apt:
    packages:
      - libchamplain-0.12-dev
      - libgtk-3-dev
      - libiio-dev
      - libchamplain-0.12-dev
      - libchamplain-gtk-0.12-dev
      - libclutter-1.0-dev
      - libclutter-gtk-1.0-dev

cache:
  cargo: true

os:
  - linux

before_script:
  - rustup component add rustfmt
  - rustup component add clippy

script:
  - cargo build
  - cargo test
  - cargo-fmt
  - cargo clippy
