[package]
name = "dashsight"
version = "0.1.0"
authors = ["Alistair Francis <alistair@alistair23.me>"]
edition = "2018"

[dependencies]
gtk = "0.8.0"
gio = "0.8.0"
gdk = "0.12.0"
cpython = "0.3.0"
gpsd_proto = "0.5.1"
