[package]
name = "dashsight"
repository = "https://github.com/alistair23/DashSight"
version = "0.1.0"
authors = ["Alistair Francis <alistair@alistair23.me>"]
edition = "2018"

[dependencies]
champlain = { git = "https://github.com/alistair23/champlain.git" }
chrono = "0.4"
cpython = "0.3.0"
gio = "0.8.0"
glib = "0.9.3"
gpsd_proto = "0.5.1"
serde = { version = "1.0.105", features = ["derive"] }

[dependencies.gtk]
version = "0.8.1"
features = ["v3_22"]
