[package]
name = "dashsight"
repository = "https://github.com/alistair23/DashSight"
version = "0.1.0"
authors = ["Alistair Francis <alistair@alistair23.me>"]
edition = "2018"

[dependencies]
ahrs = "0.2.2"
cairo-rs = "0.8.1"
champlain = { git = "https://github.com/alistair23/champlain.git" }
chrono = "0.4.11"
cpython = "0.5.0"
gio = "0.8.1"
glib = "0.9.3"
gpsd_proto = "0.6.0"
industrial-io = "0.2.0"
nalgebra = "0.18.1"
serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0.51"

[dependencies.gtk]
version = "0.8.1"
features = ["v3_22"]

[dependencies.plotters]
version = "0.2.14"
features = ["cairo"]
